image: hashicorp/terraform:1.3.7

pipelines:
  default:
    - step:
        name: Build and deploy
        services:
          - docker
        script:
          - cd metadata && npm install && npm test
          - export VERSION=$BITBUCKET_BUILD_NUMBER
          - cd ..
          - chmod +x ./scripts/deploy.sh

          - ./scripts/deploy.sh
